# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-11-27 16:56+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:35
msgid "dev mode is enabled, know more about development mode at README.md, this mode is only used for development and testing, do not enable this mode in production environment"
msgstr "开发者模式已启用，参看README.md来获取更多关于开发者模式的介绍，此模式应当仅仅在开发和测试阶段启用，请不要在生产环境中启用此模式"

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:39
msgid "debug mode is still on testing, which might cause unpredictable problems, this mode is only used for development and testing, do not enable this mode in production environment"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:122
msgid "Bad Request"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:123
msgid "Unauthorized"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:124
msgid "Forbidden"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:125
msgid "NotFound"
msgstr "未找到"

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:126
msgid "Internal Server Error"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\app.py:133
msgid "unknown: %s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:36
msgid "atri hibernate"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:68
msgid "atri started"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:78
msgid "atri start failed, got loging failure: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:81
msgid "atri start failed, got HTTP exception: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:84
msgid "atri start failed, got client connection error: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:87
msgid "atri start failed, got unknown error: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:96
msgid "atri start successfully"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:99
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:100
msgid "atri has already stopped"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:113
msgid "atri is in awaiting state"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:168
msgid "initializing musicatri facade"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:255
msgid "operation successfully"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:256
msgid "operation error"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:257
msgid "awaiting"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\bot\atri.py:258
msgid "unknown"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:32
msgid "Cannot fetch user access token"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:44
msgid "'user role' not found"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:72
msgid "role not found"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:78
msgid "permission denied"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:79
msgid "access granted"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:87
msgid "login status expired"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:94
msgid "account is not active"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\auth_service.py:107
msgid "refresh token failed"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\user_service.py:17
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\user_service.py:33
msgid "hit cache"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\user_service.py:24
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\user_service.py:41
msgid "miss hit cache"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\user_service.py:25
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\user_service.py:37
msgid "no such user"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\services\user_service.py:40
msgid "user has no roles"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\views\auth_blueprint.py:52
msgid "Login success"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\views\auth_blueprint.py:104
msgid "invalid argument"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\neo-musicatri\src\views\auth_blueprint.py:136
msgid "Logged in"
msgstr ""

